# https://ci.appveyor.com/project/culler/appveyor test

branches:
  only:
    - master

image: macOS

environment:
  matrix:
    - TESTVAR: /Users/appveyor/python38
    - TESTVAR: /Users/appveyor/python38

install:
  - sh: echo ${APPVEYOR_BUILD_WORKER_IMAGE}
  - sh: echo ${TESTVAR}
  - sh: pwd
  - sh: ls /Users/appveyor
  - sh: which python || true
  - sh: python --version || true
  - sh: which python3 || true
  - sh: python3 --version || true

  # Install required python packages
  - sh: python -m pip --target=$PYTHONPATH install cython

  - sh: ls /Users/appveyor/Library || true
  - sh: which cython || true

build:
  none

#test_script:
#  - sh: $PYTHON setup.py test
  
#after_test:
#  - sh: $PYTHON setup.py bdist_wheel

#artifacts:
#  - path: dist/*.whl

# on_success:
#   You can use this step to upload your artifacts to a public website.
#   See Appveyor's documentation for more details. Or you can simply
#   access your wheels from the Appveyor "artifacts" tab for your build.
